In [ ]:
# AIOps Mini project - numpy-aiops-anomaly detections pipeline
# A complete end to end AIOps monitoring pipeline in pure NumPy. It does exactly what a real monitoring system does — generate metrics, detect anomalies using three methods, correlate alerts across metrics, and produce an incident report.

In [5]:
# Generating metrics
import numpy as np
rng = np.random.default_rng(seed=42)
n = 180 # 3 hours one reading per minute

server_names = ['web-01', 'app-01', 'db-01']

cpu = np.column_stack([
    np.clip(rng.normal(60,5,n),0,100), #web-01 healthy
    np.clip(rng.normal(72,6,n),0,100), #app-01 running hot
    np.clip(rng.normal(45,4,n),0,100), #db-01 low usage
])

memory = np.column_stack([
    np.clip(rng.normal(65,8,n),0,100),
    np.clip(rng.normal(78,10,n),0,100),
    np.clip(rng.normal(55,6,n),0,100),
])

latency = np.column_stack([
    np.clip(rng.normal(18,3,n),0,500),
    np.clip(rng.normal(25,4,n),0,500),
    np.clip(rng.normal(12,2,n),0,500),
])

print(f"servers: {server_names}")
print(f"cpu shape: {cpu.shape}")
print("cpu metrics\n", cpu[:10].round(1)) # sample - first 10 elements
print(f"memory shape: {memory.shape}")
print("memory metrics\n", memory[:10].round(1)) # sample -frist 10 elements
print(f"latency shape: {latency.shape}")
print("latency metrics:", latency[:10].round(1))

servers: ['web-01', 'app-01', 'db-01']
cpu shape: (180, 3)
cpu metrics
 [[61.5 79.8 44.4]
 [54.8 73.3 46.5]
 [63.8 69.5 49. ]
 [64.7 78.6 40.8]
 [50.2 74.6 44.5]
 [53.5 81.2 50.9]
 [60.6 73.1 42. ]
 [58.4 64.7 41.7]
 [59.9 63.8 45.8]
 [55.7 81.9 48.4]]
memory shape: (180, 3)
memory metrics
 [[51.5 77.  57.3]
 [58.4 89.3 55.6]
 [67.  55.2 54.1]
 [63.6 63.  64.5]
 [63.  68.8 51.3]
 [63.7 92.6 67.4]
 [66.6 80.8 53.6]
 [56.9 85.7 47.3]
 [70.7 66.6 55.4]
 [70.3 66.8 48.5]]
latency shape: (180, 3)
latency metrics: [[18.7 29.  10.7]
 [17.5 25.4 12.7]
 [19.3 28.2  9.2]
 [18.2 23.2 14.9]
 [18.3 24.8 11.7]
 [16.8 24.5 12.6]
 [13.8 21.7 16.7]
 [13.4 27.6 15. ]
 [20.  27.6 11.4]
 [17.2 27.4 10.8]]


In [37]:
# baseline stastics per server
print("\n-------------baseline statistics--------------")

for i, name in enumerate(server_names):
    print(f"\n{name}")
    
    print(f"  cpu mean     : {cpu[:,i].mean():.1f}%   "
          f"std: {cpu[:,i].std():.1f}%   "
          f"p95: {np.percentile(cpu[:,i],95):.1f}%   ")

    print(f"  memory mean  : {memory[:,i].mean():.1f}%   "
          f"std: {memory[:,i].std():.1f}%   "
          f"p95: {np.percentile(cpu[:,i],95):.1f}%   " )

    print(f"  latency mean : {latency[:,i].mean():.1f}%   "
          f"std: {latency[:,i].mean():.1f}%   "
          f"p95: {np.percentile(latency[:,i],95):.1f}ms ")


-------------baseline statistics--------------

web-01
  cpu mean     : 59.7%   std: 4.3%   p95: 66.8%   
  memory mean  : 63.9%   std: 7.9%   p95: 66.8%   
  latency mean : 17.9%   std: 17.9%   p95: 22.8ms 

app-01
  cpu mean     : 72.2%   std: 6.1%   p95: 82.4%   
  memory mean  : 77.5%   std: 10.0%   p95: 82.4%   
  latency mean : 25.0%   std: 25.0%   p95: 31.5ms 

db-01
  cpu mean     : 44.9%   std: 4.1%   p95: 51.3%   
  memory mean  : 55.4%   std: 5.8%   p95: 51.3%   
  latency mean : 11.8%   std: 11.8%   p95: 15.0ms 
